version: "3"
tasks:
  # task - builds and runs the app
  default:
    cmds:
      - gradle build -x test # Build project - not tests
      - java -ea -cp build/classes/java/main VehicleRentalApp # Run the application
  # task - test
  test:
    cmds:
      - gradle test --warning-mode=none # Run tests
  # task fmt - runs the formatter
  fmt:
    cmds:
      - nix fmt
  # task lint - Ensures linting
  lint:
    deps: [fmt] # Runs task fmt first
    cmds:
      - git diff --exit-code --name-only # Exits on changes
  # Clean
  clean:
    cmds:
      - rm -rf bin/
      - rm -rf build/
      - rm -rf .gradle/
      - rm -f vehicles.txt
      - rm -f customers.txt
      - rm -f rental_records.txt
