version: "3"
tasks:
  # task - builds and runs the app
  default:
    cmds:
      - mkdir -p bin # Ensure the bin directory exists
      - javac -d bin/ -cp src src/VehicleRentalApp.java # Compile `src/` to `bin/`
      - java -ea -cp bin VehicleRentalApp # Run the application
  # task fmt - runs the formatter
  fmt:
    cmds:
      - nix fmt
  # task lint - Ensures linting
  lint:
    deps: [fmt] # Runs task fmt first
    cmds:
      - git diff --exit-code --name-only # Exits on changes
